### ISSUE TITLE
修改分区的副本数

### ISSUE THREAD

**Issue by jnhui** [Bronya0/Kafka-King#13]
没有修改分区的副本数的功能

**Comment by Bronya0** [comment]
kafka主题已经创建好后，要修改副本实际上是很麻烦的，目前我了解的kafka sdk没有什么有好的解决方法（如果有请告知，感谢），如果你确实要这么做，可以参考下官方文档：https://kafka.apache.org/documentation/#basic_ops_increase_replication_factor
新建一个json文件，配置好每个分区的副本分布，再执行kafka-reassign-partitions.sh才可以

**Comment by Bronya0** [comment]
建议集群环境下新建主题的时候，就把副本因子设置为2（或者更大），后续就不用再修改了
