### ISSUE TITLE
UI调整

### ISSUE THREAD

**Issue by ksleep** [Bronya0/Kafka-King#15]
建议拉取消息的显示数据 可以以表格或者其他形式展示，现在数据的展示虽然标有序号，但不太直观，只要单条消息超过了一行，就会感觉全在一团。

**Comment by Bronya0** [comment]
可以，但是flet框架对表格的支持不好，行数多了内存会爆炸，我当初也是因为这个没有做成表格的😂如果一次拉几万条消息一下就崩溃了，现在的实现是文本渲染，还好。后续我想想方法吧
