### ISSUE TITLE
有版本要求吗？连接不上

### ISSUE THREAD

**Issue by bearyue** [Bronya0/Kafka-King#16]
IncompatibleBrokerVersion: Kafka broker does not support the 'MetadataRequest_v0' Kafka protocol.

kafka版本：2.10

**Comment by Bronya0** [comment]
按理说0.8~2.4及以上都是支持的，我特地下载了一个kafka 2.10版本，实测也是可以正常连接的。是否是服务端做了什么特殊的配置？
![image](https://github.com/Bronya0/Kafka-King/assets/55728567/17caf7ac-9cb9-442b-9a17-ce673dab44de)
![image](https://github.com/Bronya0/Kafka-King/assets/55728567/160dd924-5d01-4a6e-805c-bd33f9abf836)
