### ISSUE TITLE
不知道怎么添加kafka cluster连接...

### ISSUE THREAD

**Issue by rr-carl-jiang** [Bronya0/Kafka-King#17]
我猜上面写的是“请在左侧添加kafka连接”？ 但是翻了一遍也没找到哪里可以添加。

<img width="799" alt="image" src="https://github.com/Bronya0/Kafka-King/assets/69362758/4b7cf45d-b0ac-4ca8-8efb-26c246438183">

**Comment by Bronya0** [comment]
啊，右上角有个加号可以添加

**Comment by rr-carl-jiang** [comment]
> 啊，右上角有个加号可以添加

<img width="1137" alt="image" src="https://github.com/Bronya0/Kafka-King/assets/69362758/ee053b93-c214-4944-9323-684e7104fd9c">

**Comment by Bronya0** [comment]
> > 啊，右上角有个加号可以添加
> 
> <img alt="image" width="1137" src="https://private-user-images.githubusercontent.com/69362758/327287116-ee053b93-c214-4944-9323-684e7104fd9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MTU4ODYsIm5iZiI6MTcxNDYxNTU4NiwicGF0aCI6Ii82OTM2Mjc1OC8zMjcyODcxMTYtZWUwNTNiOTMtYzIxNC00OTQ0LTkzMjMtNjg0ZTcxMDRmZDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDAyMDYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MjY0MGMyNGQxYjhlZWNmOTFiY2Y4N2Y2NWJhZWI0MzFkYjEyMTFlYzY4YzNlZTk3N2ZhOGEzN2RhZjBlODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HnssZOD1nnfnZ4k4_dyoourytL8qxsAJZM2DzhLQfaY">

你这是mac吗，怎么样式崩成这样😂

**Comment by Bronya0** [comment]
windows是这样的
![image](https://github.com/Bronya0/Kafka-King/assets/55728567/e47779e7-f9c1-4c2c-86e0-93d4191315e6)

**Comment by rr-carl-jiang** [comment]
> 你这是mac吗，怎么样式崩成这样😂

对的 Mac

**Comment by Bronya0** [comment]
> > 你这是mac吗，怎么样式崩成这样😂
> 
> 对的 Mac(13.6.6 (22G630))

我改天搞个mac虚拟机测试下，我没有mac环境(ToT)/

**Comment by Bronya0** [comment]
v0.24版本开始为mac下的2个架构单独构建了，你下载试试

**Comment by rr-carl-jiang** [comment]
> v0.24版本开始为mac下的2个架构单独构建了，你下载试试

试过，能看到了。谢谢。
