### ISSUE TITLE
标题栏适配明暗主题

### ISSUE THREAD

**Issue by 543566378** [Bronya0/Kafka-King#18]
windows下切换到黑色主题，但是标题栏仍然是白色，可不可以调整下？类似redis的桌面客户端TinyRDM的明暗主题那种，有强迫症，不然看着好怪。

**Comment by Bronya0** [comment]
![image](https://github.com/Bronya0/Kafka-King/assets/55728567/38c10056-5e68-4a86-8a4d-a1fa21b5c272)
标题栏是指外层窗口吗

**Comment by 543566378** [comment]
不是箭头所指的位置，而是截图上这个窗口的最外层，白色的windows自带的区域
