### ISSUE TITLE
点击无效

### ISSUE THREAD

**Issue by mcp2016** [Bronya0/Kafka-King#20]
<img width="328" alt="image" src="https://github.com/Bronya0/Kafka-King/assets/18717197/ab7d7a4b-3672-48a7-a271-01e89c8867e2">
mac m2芯片

**Comment by mcp2016** [comment]
<img width="1280" alt="image" src="https://github.com/Bronya0/Kafka-King/assets/18717197/3cc67a3e-324b-4621-907f-04e12b5a50c8">

**Comment by Bronya0** [comment]
点右边的加号，不是点下拉框

**Comment by CrTnil-N** [comment]
> 点右边的加号，不是点下拉框，mac右边没有加号吗？还是截图没截全；或者之前的版本有这个问题吗

没有加号

**Comment by withrjp** [comment]
相同的问题，m2芯片，没有加号。

**Comment by Bronya0** [comment]
V0.25版本已解决，感谢
