### ISSUE TITLE
添加连接页面没有打开的入口

### ISSUE THREAD

**Issue by mcp2016** [Bronya0/Kafka-King#23]
<img width="1280" alt="image" src="https://github.com/Bronya0/Kafka-King/assets/18717197/6bc508bc-77b1-48f1-b6f7-99a3879bf490">
这个页面只有在初次打开软件时自动打开，一旦点击左侧菜单项边无法再次找回此页面了，可以在左侧新增一个类似主页的测单

**Comment by Bronya0** [comment]
其实右上角是有常驻按钮的，但是mac显示不了，所以我放页面主体了，这样吧，我把这几个按钮放到【设置】里你看如何

**Comment by Bronya0** [comment]
已经解决，0.25版本常驻顶部
