### ISSUE TITLE
消息拉取失败

### ISSUE THREAD

**Issue by NSObjects** [Bronya0/Kafka-King#26]
![image](https://github.com/Bronya0/Kafka-King/assets/17995427/0fa2cef7-1241-43de-8b4a-6a8324a39a53)

这个提示框可以搞明显点。。

**Comment by Bronya0** [comment]
好的，下版本优化。可以细问下你的消息类型是什么吗？貌似没法utf-8解码

**Comment by NSObjects** [comment]
Protocol Buffers 编码后的数据

**Comment by Bronya0** [comment]
> Protocol Buffers 编码后的数据

那拉下来需要单独解码😂king默认现在是utf8解码，拉下来也没用吧，不过可以搞个下载功能，自己操作文件

**Comment by NSObjects** [comment]
原始数据应该可以看，只是有部分字符乱码，Kafka Assistant就可以直接看
