### ISSUE TITLE
我在ubuntu22使用，无法启动

### ISSUE THREAD

**Issue by lisongxi** [Bronya0/Kafka-King#36]
报错信息
/.flet/bin/flet-0.23.2/flet/flet: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory

**Comment by Bronya0** [comment]
ubuntu需要安装依赖：sudo apt install libmpv1
参考：https://stackoverflow.com/questions/78007193/error-while-loading-shared-libraries-libmpv-so-1-cannot-open-shared-object-fil
