### ISSUE TITLE
0.31内网环境无法使用

### ISSUE THREAD

**Issue by 1104817655** [Bronya0/Kafka-King#44]
内网环境提示一下报错
the webview2 runtime is required 
press ok to download and install
note the installer will download silently so please wait

**Comment by 1104817655** [comment]
v0.31 版本

**Comment by Bronya0** [comment]
你的电脑没有webview

**Comment by Bronya0** [comment]
点ok给你跳转过去安装

**Comment by 1104817655** [comment]
纯内网环境，不能上网

**Comment by Bronya0** [comment]
> 纯内网环境，不能上网

下载个webview安装包，丢进去安装（或者直接装edge浏览器也行）

**Comment by ChunChunWeb** [comment]
![image](https://github.com/user-attachments/assets/78823c01-e743-4c60-9e96-7dbc0e24598d)

**Comment by ChunChunWeb** [comment]
一样内网环境，检查更新能不能设置为关闭？

**Comment by Bronya0** [comment]
> 一样内网环境，检查更新能不能设置为关闭？

检查更新不会使软件崩溃，你这个是系统的webview组件问题

**Comment by Bronya0** [comment]
https://blog.csdn.net/weixin_46570843/article/details/143169346
