### ISSUE TITLE
切换窗口时直接报错退出

### ISSUE THREAD

**Issue by ChunChunWeb** [Bronya0/Kafka-King#45]
![image](https://github.com/user-attachments/assets/3608660f-8c85-445f-b418-eb3e84e94406)

在使用alt+ table 时出现，操作系统为win10，虚拟云桌面。

**Comment by Bronya0** [comment]
看着是你这个云桌面的系统问题。参考：https://blog.csdn.net/weixin_46570843/article/details/143169346

**Comment by ChunChunWeb** [comment]
解决了，重新安装了WebView2，感谢
