### ISSUE TITLE
首次进入 topic 页面时报错

### ISSUE THREAD

**Issue by sugarlesss** [Bronya0/Kafka-King#50]
报错：request ListGroups has 1 separate shard errors, first: unable to dial: dial tcp: lookup kafka: no such host
![image](https://github.com/user-attachments/assets/000abecb-5964-4759-b9f4-d8e0db276ddf)

看起来是 host 没找到，但我填的是 ip，不知道还要怎么配 host

**Comment by Bronya0** [comment]
你填的是ip也要配hosts，这是kafka的广播机制决定的。
![局部截取_20241216_183140](https://github.com/user-attachments/assets/4d24f6a4-6c17-4736-b3a6-d8d789231d0d)

**Comment by sugarlesss** [comment]
感谢！
